version: "2"
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
exclude_patterns:
  - ".circleci"
  - ".git"
  - ".codeclimate.yml"
  - ".gitignore"
  - "c.out"
  - "coverage"
  - "Gopkg.*"
  - "Makefile"
  - "vendor"
  - "**/*.md"
  - "**/*_test.go"