version: "2"
plugins:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
exclude_patterns:
  - ".circleci"
  - ".git"
  - ".gitignore"
  - ".codeclimate.yml"
  - "c.out"
  - "coverage"
  - "CODE_OF_CONDUCT.md"
  - "Gopkg.lock"
  - "Gopkg.toml"
  - "LICENSE.md"
  - "Makefile"
  - "README.md"
  - "vendor"